-- start.script

function init(self)
	print("start screen")
	msg.post(".", "acquire_input_focus")
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		msg.post('main:/go', "load_main_menu")
	end
end
