go.property("speed", 1000)
go.property("direction", vmath.vector3(1,0,0))

function init(self)
	-- Self delete after some time
	timer.delay(5, false, function() go.delete() end)
end

function fixed_update(self, dt)
	-- Bullet movement
	local pos = go.get_position()
	pos = pos + self.direction * self.speed * dt
	go.set_position(pos)
end

function on_message(self, message_id, message, sender)
	-- on_message
end
