function init(self)
	--
	-- go.animate("/sprite#sprite", "color_add.w", go.PLAYBACK_ONCE_PINGPONG, 1, go.EASING_INQUAD, 1)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("trigger_response") and message.enter then
		-- delete the bullet
		go.delete(message.other_id)
		-- print("colidiu!")
		go.set("/sprite#sprite", "color_add.w", 0)
		go.animate("/sprite#sprite", "color_add.w", go.PLAYBACK_ONCE_PINGPONG, 0.5, go.EASING_INQUAD, 0.3)
	end
end
