-- basic_green_bullet.script

function init(self)
	self.speed = 300
	self.direction = vmath.vector3(-1,0,0)
	-- self delete after some time
	timer.delay(5, false, function() go.delete() end)
end

function fixed_update(self, dt)
	-- Update the bullet position based on velocity
	local pos = go.get_position()
	pos = pos + self.direction * self.speed * dt
	go.set_position(pos)
end

function on_message(self, message_id, message, sender)
	-- on_message
end
